BATCH_SIZE=$1

# Baselines w/o SDPA
mkdir -p /fsx-checkpoints/yejinlee/paper_submission_results/latency_distribution_w_warmup/wo_sdpa/1gpu_1node/batched/S2ST/
mkdir -p /fsx-checkpoints/yejinlee/paper_submission_results/latency_distribution_w_warmup/wo_sdpa/1gpu_1node/batched/S2TT/
mkdir -p /fsx-checkpoints/yejinlee/paper_submission_results/latency_distribution_w_warmup/wo_sdpa/1gpu_1node/batched/T2TT/
mkdir -p /fsx-checkpoints/yejinlee/paper_submission_results/latency_distribution_w_warmup/wo_sdpa/1gpu_1node/batched/T2ST/
DISABLE_SDPA=1 EFFECTIVE_BATCH_SIZE=$BATCH_SIZE m4t_evaluate --data_file /fsx-atom/shared/yejinlee_backups/seamless_dataset2/test_manifest.json --task S2ST --tgt_lang spa --output_path ./test --ref_field tgt_text --audio_root_dir /fsx-atom/shared/yejinlee_backups/seamless_dataset2/downloads/extracted/7411e52500e75f4587cdf715b30663e27f8e5f4865174435569bffe9b3899945/test --model_name seamlessM4T_v2_large --batch_size 1 > "/fsx-checkpoints/yejinlee/paper_submission_results/latency_distribution_w_warmup/wo_sdpa/1gpu_1node/batched/S2ST/batch_size_${BATCH_SIZE}_stat"
DISABLE_SDPA=1 EFFECTIVE_BATCH_SIZE=$BATCH_SIZE m4t_evaluate --data_file /fsx-atom/shared/yejinlee_backups/seamless_dataset2/test_manifest.json --task S2TT --tgt_lang spa --output_path ./test --ref_field tgt_text --audio_root_dir /fsx-atom/shared/yejinlee_backups/seamless_dataset2/downloads/extracted/7411e52500e75f4587cdf715b30663e27f8e5f4865174435569bffe9b3899945/test --model_name seamlessM4T_v2_large --batch_size 1 > "/fsx-checkpoints/yejinlee/paper_submission_results/latency_distribution_w_warmup/wo_sdpa/1gpu_1node/batched/S2TT/batch_size_${BATCH_SIZE}_stat"
DISABLE_SDPA=1 EFFECTIVE_BATCH_SIZE=$BATCH_SIZE m4t_evaluate --data_file /fsx-atom/shared/yejinlee_backups/seamless_dataset2/test_manifest.json --task T2TT --tgt_lang spa --output_path ./test --ref_field tgt_text --audio_root_dir /fsx-atom/shared/yejinlee_backups/seamless_dataset2/downloads/extracted/7411e52500e75f4587cdf715b30663e27f8e5f4865174435569bffe9b3899945/test --model_name seamlessM4T_v2_large --batch_size 1 > "/fsx-checkpoints/yejinlee/paper_submission_results/latency_distribution_w_warmup/wo_sdpa/1gpu_1node/batched/T2TT/batch_size_${BATCH_SIZE}_stat"
DISABLE_SDPA=1 EFFECTIVE_BATCH_SIZE=$BATCH_SIZE m4t_evaluate --data_file /fsx-atom/shared/yejinlee_backups/seamless_dataset2/test_manifest.json --task T2ST --tgt_lang spa --output_path ./test --ref_field tgt_text --audio_root_dir /fsx-atom/shared/yejinlee_backups/seamless_dataset2/downloads/extracted/7411e52500e75f4587cdf715b30663e27f8e5f4865174435569bffe9b3899945/test --model_name seamlessM4T_v2_large --batch_size 1 > "/fsx-checkpoints/yejinlee/paper_submission_results/latency_distribution_w_warmup/wo_sdpa/1gpu_1node/batched/T2ST/batch_size_${BATCH_SIZE}_stat"
